### PR TITLE
add filename to mediaitem

### PR DESCRIPTION
**Pull request by skpenpen**

### CODE REVIEW

**Comment by skpenpen** [comment]
I signed it!

**Comment by jba** [comment]
This is generated code. We have to update the discovery doc (the json file). Do you have a recent one? It doesn't seem to be in the list of public docs.

Also, we use Gerritt for PRs, so unless you want to learn that, just point me to the discovery doc and I'll make the change.

**Comment by skpenpen** [comment]
Do you mean https://github.com/skpenpen/google-api-go-client/blob/master/photoslibrary/v1/photoslibrary-api.json ?

**Comment by jba** [comment]
I'm sorry, we can't accept this PR. You should file a feature request with the Photos Library API directly at  https://developers.google.com/photos/library/support/how-to-get-help.

**Pull request closed without merging**
