### PR TITLE
Add notice on library maintenance mode

### PR DESCRIPTION
**Pull request by danoscarmike**
@jba, @broady please review

### CODE REVIEW

**Comment by broady** [comment]
Please send a pull request via Gerrit.

https://github.com/google/google-api-go-client/blob/master/CONTRIBUTING.md#code-review

Happy to clone this over there if you don't want to.

**Comment by danoscarmike** [comment]
Of course, will do.  Was on a roll through 7 languages and forgot about this for Go... :(

**Comment by broady** [comment]
Sorry.

**Comment by danoscarmike** [comment]
No apology necessary, my fault.  Change sent for review on Gerrit.

**Pull request closed without merging**
